# Generated by Django 5.2.1 on 2025-05-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerhere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
