apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: portfolio
spec:
  type: LoadBalancer
  ports:
    - port: 80 # or another port
      targetPort: 8000
  selector:
    app: portfolio
